config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :songs

  namespace :api do
    namespace :v1 do
      resources :songs, only: [:index]
    end
  end

  root "public#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/playlist.rb
class Playlist < ApplicationRecord
end

app/models/song.rb
class Song < ApplicationRecord
  validates :filename, presence: true

  scope :by_recent, -> { order(created_at: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/songs_controller.rb
module Api
  module V1
    class SongsController < ApplicationController
      def index
        songs = SongsCollectorService.new.call
        render json: { message: 'test', songs: songs }, status: 200
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def index
    @songs = Song.by_recent
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :authenticate_user!

  def index
    @songs = Song.where(created_at: :desc)
  end

  def new
    @song = Song.new
  end

  def create
    blob = upload_file

    # raise blob.key.inspect
    @song = Song.new({filename: blob.filename, blob_key: blob.key, content_type: blob.content_type})
    if @song.save 
      redirect_to root_path, notice: "Song saved."
    else
      redirect_to :new, alert: "Error saving song."
    end
    
  end

  private

  def upload_file
    ActiveStorage::Blob.create_and_upload!(io: song_params[:song], filename: song_params[:song].original_filename)
  end

  def song_params
    params.require(:song).permit(:song)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/song_helper.rb
module SongHelper
  def song_path(song)
    rails_storage_proxy_path(ActiveStorage::Blob.find_by(key: song.blob_key))
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navbar', formats: :html %>

    <% if notice %>
      <div class="alert alert-info" role="alert" data-controller='flash'>
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close" data-action="click->flash#close">
          <span aria-hidden="true" >&times;</span>
        </button>
      </div>
    <% end %>

    <% if alert %>
      <div class="alert alert-danger" role="alert" data-controller='flash'>
        <%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close" data-action="click->flash#close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="container-fluid px-0">
  <nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">
        <%= image_tag "music_logo.png", size: '50x50' %>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to 'New Song', new_song_path, class: "nav-link active" %>
          </li>
        </ul>
        <form class="">
          <% if current_user %>
            <div class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= current_user.username %>
              </a>
              <ul class="dropdown-menu">
                <li> 
                  <%= link_to "Logout", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
                </li>
              </ul>
            </div>
          <% else %>
            <%= link_to "Login", new_user_session_path, class: "btn btn-primary mr-2" %>
            <%= link_to "New Member", new_user_registration_path, class: "btn btn-outline-success" %>
          <% end %>
        </form>
      </div>
    </div>
  </nav>
</div>

app/views/songs/new.html.erb
<div class="container">
  <h3>Upload new song</h3>
  <%= form_for(@song, :html => {:enctyope => "multipart/alternative"}) do |f| %>
    <%= f.file_field :song %>

    <%= f.submit 'Submit' %>
  <% end %>
</div>